---
title: "ESM"
author: "Fonti Kar"
date: "`r Sys.Date()`"
output:
  word_document:
    reference_docx: Style_guide.docx
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, eval = TRUE, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(eval = FALSE,
                      echo = FALSE, 
                      include = FALSE, 
                      warning = FALSE,
                      message = FALSE)
rm(list=ls())
sessionInfo()

# R version 3.6.1 (2019-07-05)
# Platform: x86_64-apple-darwin15.6.0 (64-bit)
# Running under: macOS High Sierra 10.13.6

pacman::p_load(dplyr, magrittr, ggplot2, purrr, Rphylopars, phytools, GGally, mice, janitor, patchwork, GGally, psych, brms, mi, pander,latex2exp, stringr, bayestestR, brms, metaDigitise)

my_theme <- theme(#legend.position = "none",
  legend.position = "bottom",
  legend.text =element_text(size = 14),
  legend.title =element_text(size = 14, face = "bold"),
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank(),
  axis.text=element_text(size=16),
  axis.title=element_text(size=16),
  plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
  plot.background = element_rect(colour = "white"))

source("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/R/functions/helper.R")
```

```{r, eval = TRUE}
## Read in data
data <-read.csv("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/data/processed/Long_Tinc_MR.csv", stringsAsFactors = F)
mi_data <-read.csv("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/data/processed/Long_Tinc_MR_MI.csv", stringsAsFactors = F)
```

## Heterogenous variance 
Model with homogenous variance was best supported by WAIC values. As such, we did not explicitly model residuals in all subsequent models
```{r, eval = TRUE}
mod.4.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/mod.4.obj") #Intercept ME HOMO
mod.4.het.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/mod.4.het.obj") #Intercept ME Hetero

#Add IC
waic_mod.4.obj<- waic(mod.4.obj)

waic_mod.4.het.obj <- waic(mod.4.het.obj)

#Compare
WAIC_compare_resid <- loo_compare(waic_mod.4.obj, waic_mod.4.het.obj)

#Creating table
Resid_compare_WAIC <- data.frame(matrix(nrow = 2, ncol = 4))
colnames(Resid_compare_WAIC) <- c("Model", "WAIC value", "ELPD Diff", "SE Diff")
Resid_compare_WAIC$Model <- c("Homogenous residuals", "Heterogenous residuals")

#WAIC
Resid_compare_WAIC[1,2] <- waic_mod.4.obj$estimates[3,1] %>% round(2)
Resid_compare_WAIC[2,2] <- waic_mod.4.het.obj$estimates[3,1] %>% round(2)

#ELPD and SE
#WAIC
Resid_compare_WAIC[1,3] <- WAIC_compare_resid[1,1] %>% round(2)
Resid_compare_WAIC[2,3] <- WAIC_compare_resid[2,1] %>% round(2)

Resid_compare_WAIC[1,4] <- WAIC_compare_resid[1,2] %>% round(2)
Resid_compare_WAIC[2,4] <- WAIC_compare_resid[2,2] %>% round(2)
```

```{r, eval = TRUE, include = TRUE}
pander(Resid_compare_WAIC,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S1 Comparisons of WAIC values for homogenous and hetergenous residuals")
```
```{r, eval = TRUE}
#Testing whether treatments differed in their reaction norms
#Tabulate the model coefficients for all CC model
#Read in models
cc_mod.1.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_mod.z1.obj")
cc_mod.3.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_mod.z3.obj")

#Model without interaction
#Extract entire posterior
cc_mod.1_post <- posterior_samples(cc_mod.1.obj)
#Names of each column
colnames(cc_mod.1_post)[1:11]

#Combining the coefficients from the final model
#Getting the fixed effects
cc_mod.1_fixed <- cc_mod.1_post[1:5] %>% posterior_summary() %>% round(3) 

#Getting the SD 
cc_mod.1_sd <- posterior_samples(cc_mod.1.obj, "sd_")
cc_mod.1_var <- cc_mod.1_sd^2 
names(cc_mod.1_var) <- str_replace(names(cc_mod.1_var), "sd", "var")
cc_mod.1_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
cc_mod.1_cov <- posterior_samples(cc_mod.1.obj, "cor_") * (cc_mod.1_sd[,1] * cc_mod.1_sd[,2])
names(cc_mod.1_cov) <- str_replace(names(cc_mod.1_cov), "cor", "cov")

cc_mod.1_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
cc_mod.1_residuals <- ( posterior_samples(cc_mod.1.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
cc_mod.1_coeffs <- rbind(cc_mod.1_fixed,
                         cc_mod.1_var %>% posterior_summary() %>% round(3),
                         cc_mod.1_cov %>% posterior_summary() %>% signif(3),
                         cc_mod.1_residuals)

#Excluding est. error
cc_mod.1_coeffs <- cc_mod.1_coeffs[,c(1,3,4)]
#Rownames as col
cc_mod.1_coeffs <- as.data.frame(cc_mod.1_coeffs)
cc_mod.1_coeffs$Parameter <- c(rownames(cc_mod.1_coeffs))
rownames(cc_mod.1_coeffs) <- NULL 
cc_mod.1_coeffs <- cc_mod.1_coeffs[,c(4,1:3)]

#Full model
#Extract entire posterior
cc_mod.3_post <- posterior_samples(cc_mod.3.obj)
#Names of each column
colnames(cc_mod.3_post)[1:12]

#Combining the coefficients from the final model
#Getting the fixed effects
cc_mod.3_fixed <- cc_mod.3_post[1:6] %>% posterior_summary() %>% round(3) 

#Getting the SD 
cc_mod.3_sd <- posterior_samples(cc_mod.3.obj, "sd_")
cc_mod.3_var <- cc_mod.3_sd^2 
names(cc_mod.3_var) <- str_replace(names(cc_mod.3_var), "sd", "var")
cc_mod.3_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
cc_mod.3_cov <- posterior_samples(cc_mod.3.obj, "cor_") * (cc_mod.3_sd[,1] * cc_mod.3_sd[,2])
names(cc_mod.3_cov) <- str_replace(names(cc_mod.3_cov), "cor", "cov")

cc_mod.3_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
cc_mod.3_residuals <- ( posterior_samples(cc_mod.3.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
cc_mod.3_coeffs <- rbind(cc_mod.3_fixed,
                         cc_mod.3_var %>% posterior_summary() %>% round(3),
                         cc_mod.3_cov %>% posterior_summary() %>% signif(3),
                         cc_mod.3_residuals)

#Excluding est. error
cc_mod.3_coeffs <- cc_mod.3_coeffs[,c(1,3,4)]
#Rownames as col
cc_mod.3_coeffs <- as.data.frame(cc_mod.3_coeffs)
cc_mod.3_coeffs$Parameter <- c(rownames(cc_mod.3_coeffs))
rownames(cc_mod.3_coeffs) <- NULL 
cc_mod.3_coeffs <- cc_mod.3_coeffs[,c(4,1:3)]
```

```{r, eval = TRUE}
#Tabulating the imputation model with main effects only
#Read in model
mod.imp.1.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/mod.imp.z1")

#Extract entire posterior
mod.imp.1_post <- posterior_samples(mod.imp.1.obj)
#Names of each column
colnames(mod.imp.1_post)[1:15]

#Combining the coefficients from the final model
#Getting the fixed effects
mod.imp.1_fixed <- mod.imp.1_post[1:6] %>% posterior_summary() %>% round(3) 

#Getting the SD 
mod.imp.1_sd <- posterior_samples(mod.imp.1.obj, "sd_")
mod.imp.1_var <- mod.imp.1_sd^2 
names(mod.imp.1_var) <- str_replace(names(mod.imp.1_var), "sd", "var")
mod.imp.1_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
mod.imp.1_cov <- posterior_samples(mod.imp.1.obj, "cor_") * (mod.imp.1_sd[,1] * mod.imp.1_sd[,2])
names(mod.imp.1_cov) <- str_replace(names(mod.imp.1_cov), "cor", "cov")

mod.imp.1_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
mod.imp.1_residuals <- ( posterior_samples(mod.imp.1.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
mod.imp.1_coeffs <- rbind(mod.imp.1_fixed,
                         mod.imp.1_var %>% posterior_summary() %>% round(3),
                         mod.imp.1_cov %>% posterior_summary() %>% signif(3),
                         mod.imp.1_residuals)

#Excluding est. error
mod.imp.1_coeffs <- mod.imp.1_coeffs[,c(1,3,4)]
#Rownames as col
mod.imp.1_coeffs <- as.data.frame(mod.imp.1_coeffs)
mod.imp.1_coeffs$Parameter <- c(rownames(mod.imp.1_coeffs))
rownames(mod.imp.1_coeffs) <- NULL 
mod.imp.1_coeffs <- mod.imp.1_coeffs[,c(4,1:3)] 
```

```{r, eval = TRUE, include = TRUE}
pander(cc_mod.3_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S2 Model coefficients of full model testing whether developmental temperature affects the elevation and slope of the thermal reaction norm of metabolic rate. This model used a complete case dataset, n = 3818")

pander(mod.imp.1_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S3 Model coefficients of main effects model testing developmental temperature affects the elevation of the thermal reaction norm of metabolic rate. Output of this model was generated from an imputation analysis, n = 6000")

pander(cc_mod.1_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S4 Model coefficients of main effects model testing developmental temperature affects the elevation of the thermal reaction norm of metabolic rate. This model used a complete case dataset, n = 3818")

```

```{r, eval = TRUE, cache = TRUE}
cc_mod.3.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_mod.3.obj")

#Make a figure from model predictions using cc_mod.2.obj
cc_mod.3.imp.post <- posterior_samples(cc_mod.3.obj) 
names(cc_mod.3.imp.post)[1:12]

#Setting up predictive data
new_data <- mi_data %>% distinct(id, samp_session, temp, treatment)

#Specificying the posterior
post = cc_mod.3.imp.post

#Try fucking pmap    
model_predictions <- bind_rows(pmap(new_data, mr_pred))
str(model_predictions)
rownames(model_predictions) <- NULL

#Check it
model_predictions %>% filter(id == "ld0449") #Fantastic

#Change ID to character
model_predictions %<>%  mutate(id = as.character(id))

#Plot it
cold_ids <- model_predictions %>% filter(treatment == 23) %>% pull(id) %>% unique()
hot_ids <- model_predictions %>% filter(treatment == 29) %>% pull(id) %>% unique()

set.seed(7)
subset_cold <- sample(cold_ids, 10 , replace = F)

set.seed(7)
subset_hot <- sample(hot_ids, 10 , replace = F)
```

```{r, eval = TRUE, include = TRUE, fig.height = 6.7, fig.width = 9.5}
#Filter out the subset IDS
model_predictions %>% filter(id %in% c(subset_cold, subset_hot) & samp_session %in% c(1,5,10)) %>% 
  ggplot(aes(x = temp, y = mean_lnmr)) + 
  geom_line(aes(group = id, colour = factor(treatment)), stat="smooth", method = "lm", lwd = 0.5, alpha = 0.5) + 
  geom_line(aes(group = factor(treatment), colour = factor(treatment)), stat="smooth", method = "lm", lwd = 2, alpha = 1, position=position_dodge(width = 0.3)) +
  geom_point(alpha = 0.2) + 
  facet_wrap(~samp_session) + 
  scale_colour_manual(values = c("#2790F3", "#F24D2A")) + 
  scale_x_continuous(breaks = c(seq(24,34, by = 2))) + 
  scale_y_continuous(lim = c(-6.5, -5.5)) + 
  labs(x = "Temperature",
       y = TeX("log VCO_2 per minute"),
       #title = "Relative contribution of variance over age",
       colour =  "Treatment") + 
  theme_bw() +
  my_theme + 
  theme(legend.position = "none",
        strip.text = element_text(size = 18),
        strip.background = element_blank())
```

```{r, eval = TRUE}
#Treatment differences in temperature specific repeatabilty using complete case models
# Read in models
cc_cold.2.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_cold.2.obj.z")
cc_hot.2.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_hot.2.obj.z")

#Poster names
names(posterior_samples(cc_cold.2.obj))[1:10]

#Temp define:
temp <- seq(24,34, by = 2)
z_temp <- scale(temp)[,1]
#map(new_data %>% select(temp) %>% distinct(), brms_rpt) #Can't get this to work

cold_rpt <- bind_rows(lapply(z_temp, function(x) brms_rpt(x, model = cc_cold.2.obj)))
cold_rpt %<>%  mutate(treatment = "cold")

hot_rpt <- bind_rows(lapply(z_temp, function(x) brms_rpt(x, model = cc_hot.2.obj)))
hot_rpt %<>%  mutate(treatment = "hot")

rpt_data <- bind_rows(cold_rpt, hot_rpt)
rpt_data %<>% mutate(temp = rep(seq(24,34, by = 2),2)) 

#Posterior mode
cold_rpt_mode <- bind_rows(lapply(z_temp, function(x) brms_rpt(x, model = cc_cold.2.obj, type = "mode")))
cold_rpt_mode %<>%  mutate(treatment = "cold")

hot_rpt_mode <- bind_rows(lapply(z_temp, function(x) brms_rpt(x, model = cc_hot.2.obj, type = "mode")))
hot_rpt_mode %<>%  mutate(treatment = "hot")

rpt_data_mode <- bind_rows(cold_rpt_mode, hot_rpt_mode)
```

```{r, eval = TRUE, include = TRUE, fig.height = 6.7, fig.width = 9.5, cache = TRUE}
#plot this
ggplot(rpt_data, aes(x = factor(temp), y = rpt, group = treatment, colour = treatment)) + 
  geom_point(position = position_dodge(0.5), size = 4) + 
  geom_errorbar(aes(ymin = Lower, ymax = Upper), width = 0, position = position_dodge(0.5), size = 0.6) +
  scale_colour_manual(values = c("#2790F3", "#F24D2A")) + 
  ylim(c(0, 0.4)) + 
  labs(x = "Temperature",
       y = "Repeatability",
       colour =  "Treatment") + 
  theme_bw() +
  my_theme + 
  theme(legend.position = "none") 
```

```{r, eval = TRUE, include= TRUE}
#Tabulating repeatability at each temperature
rpt_data %<>% select(treatment, temp:Upper)

pander(rpt_data,
       justify = "lcccc",
       #split.cell = 80,
       caption = "Table S5 Temeprature specific, adjusted repeatability estimates of log transformed metabolic rate for lizards from two developmental temperatures (n_hot = 25, n_cold = 26). These values were estimated from complete case dataset, n_obs = 3818")
```

```{r, eval = TRUE}
#Model coefficients for hot and cold imputation models that were used to estimate T specific repeatability
# Read in models
cold_imp.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cold.mod.imp.3.z")
hot_imp.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/hot.mod.imp.3.z")

#Extract entire posterior
cold_imp.post <- posterior_samples(cold_imp.obj)
#Names of each column
colnames(cold_imp.post)[1:12]

#Combining the coefficients from the final model
#Getting the fixed effects
cold_imp_fixed <- cold_imp.post[1:5] %>% posterior_summary() %>% round(3) 

#Getting the SD 
cold_imp_sd <- posterior_samples(cold_imp.obj, "sd_")
cold_imp_var <- cold_imp_sd^2 
names(cold_imp_var) <- str_replace(names(cold_imp_var), "sd", "var")
cold_imp_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
cold_imp_cov <- posterior_samples(cold_imp.obj, "cor_") * (cold_imp_sd[,1] * cold_imp_sd[,2])
names(cold_imp_cov) <- str_replace(names(cold_imp_cov), "cor", "cov")

cold_imp_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
cold_imp_residuals <- ( posterior_samples(cold_imp.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
cold_imp_coeffs <- rbind(cold_imp_fixed,
                         cold_imp_var %>% posterior_summary() %>% round(3),
                         cold_imp_cov %>% posterior_summary() %>% signif(3),
                         cold_imp_residuals)

#Excluding est. error
cold_imp_coeffs <- cold_imp_coeffs[,c(1,3,4)]
#Rownames as col
cold_imp_coeffs <- as.data.frame(cold_imp_coeffs)
cold_imp_coeffs$Parameter <- c(rownames(cold_imp_coeffs))
rownames(cold_imp_coeffs) <- NULL 
cold_imp_coeffs <- cold_imp_coeffs[,c(4,1:3)]

#Extract entire posterior
hot_imp.post <- posterior_samples(hot_imp.obj)
#Names of each column
colnames(hot_imp.post)[1:12]

#Combining the coefficients from the final model
#Getting the fixed effects
hot_imp_fixed <- hot_imp.post[1:5] %>% posterior_summary() %>% round(3) 

#Getting the SD 
hot_imp_sd <- posterior_samples(hot_imp.obj, "sd_")
hot_imp_var <- hot_imp_sd^2 
names(hot_imp_var) <- str_replace(names(hot_imp_var), "sd", "var")
hot_imp_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
hot_imp_cov <- posterior_samples(hot_imp.obj, "cor_") * (hot_imp_sd[,1] * hot_imp_sd[,2])
names(hot_imp_cov) <- str_replace(names(hot_imp_cov), "cor", "cov")

hot_imp_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
hot_imp_residuals <- ( posterior_samples(hot_imp.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
hot_imp_coeffs <- rbind(hot_imp_fixed,
                         hot_imp_var %>% posterior_summary() %>% round(3),
                         hot_imp_cov %>% posterior_summary() %>% signif(3),
                         hot_imp_residuals)
#Excluding est. error
hot_imp_coeffs <- hot_imp_coeffs[,c(1,3,4)]
#Rownames as col
hot_imp_coeffs <- as.data.frame(hot_imp_coeffs)
hot_imp_coeffs$Parameter <- c(rownames(hot_imp_coeffs))
rownames(hot_imp_coeffs) <- NULL 
hot_imp_coeffs <- hot_imp_coeffs[,c(4,1:3)]
```

```{r, eval = TRUE, include = TRUE}
pander(cold_imp_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S6 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. This imputation model used an subset dataset of lizards in the cold developmental temperature only n = 26, n_obs = ")

pander(hot_imp_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S7 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. This imputation model used an subset dataset of lizards in the hot developmental temperature only n = 25, n_obs = ")
```

```{r, eval = TRUE}
#Model coefficients for hot and cold cc models that were used to estimate T specific repeatability
# Read in models
cc_cold.2.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_cold.2.obj.z")
cc_hot.2.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_hot.2.obj.z")

#Extract entire posterior
cc_cold.post <- posterior_samples(cc_cold.2.obj)
#Names of each column
colnames(cc_cold.post)[1:10]

#Combining the coefficients from the final model
#Getting the fixed effects
cc_cold_fixed <- cc_cold.post[1:4] %>% posterior_summary() %>% round(3) 

#Getting the SD 
cc_cold_sd <- posterior_samples(cc_cold.2.obj, "sd_")
cc_cold_var <- cc_cold_sd^2 
names(cc_cold_var) <- str_replace(names(cc_cold_var), "sd", "var")
cc_cold_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
cc_cold_cov <- posterior_samples(cc_cold.2.obj, "cor_") * (cc_cold_sd[,1] * cc_cold_sd[,2])
names(cc_cold_cov) <- str_replace(names(cc_cold_cov), "cor", "cov")

cc_cold_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
cc_cold_residuals <- ( posterior_samples(cc_cold.2.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
cc_cold_coeffs <- rbind(cc_cold_fixed,
                         cc_cold_var %>% posterior_summary() %>% round(3),
                         cc_cold_cov %>% posterior_summary() %>% signif(3),
                         cc_cold_residuals)

#Excluding est. error
cc_cold_coeffs <- cc_cold_coeffs[,c(1,3,4)]
#Rownames as col
cc_cold_coeffs <- as.data.frame(cc_cold_coeffs)
cc_cold_coeffs$Parameter <- c(rownames(cc_cold_coeffs))
rownames(cc_cold_coeffs) <- NULL 
cc_cold_coeffs <- cc_cold_coeffs[,c(4,1:3)]

#Extract entire posterior
cc_hot.post <- posterior_samples(cc_hot.2.obj)
#Names of each column
colnames(cc_hot.post)[1:10]

#Combining the coefficients from the final model
cc_hot_fixed <- cc_hot.post[1:4] %>% posterior_summary() %>% round(3) 

#Getting the SD 
cc_hot_sd <- posterior_samples(cc_hot.2.obj, "sd_")
cc_hot_var <- cc_hot_sd^2 
names(cc_hot_var) <- str_replace(names(cc_hot_var), "sd", "var")
cc_hot_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
cc_hot_cov <- posterior_samples(cc_hot.2.obj, "cor_") * (cc_hot_sd[,1] * cc_hot_sd[,2])
names(cc_hot_cov) <- str_replace(names(cc_hot_cov), "cor", "cov")

cc_hot_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
cc_hot_residuals <- ( posterior_samples(cc_hot.2.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
cc_hot_coeffs <- rbind(cc_hot_fixed,
                         cc_hot_var %>% posterior_summary() %>% round(3),
                         cc_hot_cov %>% posterior_summary() %>% signif(3),
                         cc_hot_residuals)
#Excluding est. error
cc_hot_coeffs <- cc_hot_coeffs[,c(1,3,4)]
#Rownames as col
cc_hot_coeffs <- as.data.frame(cc_hot_coeffs)
cc_hot_coeffs$Parameter <- c(rownames(cc_hot_coeffs))
rownames(cc_hot_coeffs) <- NULL 
cc_hot_coeffs <- cc_hot_coeffs[,c(4,1:3)]
```

```{r, eval = TRUE, include = TRUE}
pander(cc_cold_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S7 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. This model used a complete case dataset of lizards in the cold developmental temperature only n = 26, n_obs = 1897")

pander(cc_hot_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S9 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. This imputation model used a complete case dataset of lizards in the hot developmental temperature only n = 25, n_obs = 1921")
```

```{r, eval = TRUE}
#Model coefficients for hot and cold imputation models that were used to estimate repeatbility of slopes
# Read in models
cold.mod.imp.4 <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cold.mod.imp.z4")
hot.mod.imp.4 <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/hot.mod.imp.z4")

#Extract entire posterior
cold_imp.4.post <- posterior_samples(cold.mod.imp.4)
#Names of each column
colnames(cold_imp.4.post)[1:13]

#Combining the coefficients from the final model
#Getting the fixed effects
cold_imp.4_fixed <- cold_imp.4.post[1:5] %>% posterior_summary() %>% round(3) 

#Getting the SD 
cold_imp.4_sd <- posterior_samples(cold.mod.imp.4, "sd_")
cold_imp.4_var <- cold_imp.4_sd^2 
names(cold_imp.4_var) <- str_replace(names(cold_imp.4_var), "sd", "var")
cold_imp.4_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
cold_imp.4_cov <- bind_cols(posterior_samples(cold.mod.imp.4, "cor_")[,1] * (cold_imp.4_sd[,1] * cold_imp.4_sd[,2]),
                            posterior_samples(cold.mod.imp.4, "cor_")[,2] * (cold_imp.4_sd[,3] * cold_imp.4_sd[,4]))
names(cold_imp.4_cov) <- str_replace(names(posterior_samples(cold.mod.imp.4, "cor_")), "cor", "cov")
cold_imp.4_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
cold_imp.4_residuals <- ( posterior_samples(cold.mod.imp.4, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
cold_imp.4_coeffs <- rbind(cold_imp.4_fixed,
                         cold_imp.4_var %>% posterior_summary() %>% round(3),
                         cold_imp.4_cov %>% posterior_summary() %>% signif(3),
                         cold_imp.4_residuals)

#Excluding est. error
cold_imp.4_coeffs <- cold_imp.4_coeffs[,c(1,3,4)]
#Rownames as col
cold_imp.4_coeffs <- as.data.frame(cold_imp.4_coeffs)
cold_imp.4_coeffs$Parameter <- c(rownames(cold_imp.4_coeffs))
rownames(cold_imp.4_coeffs) <- NULL 
cold_imp.4_coeffs <- cold_imp.4_coeffs[,c(4,1:3)]

#Extract entire posterior
hot_imp.4.post <- posterior_samples(hot.mod.imp.4)
#Names of each column
colnames(hot_imp.4.post)[1:13]

#Combining the coefficients from the final model
#Getting the fixed effects
hot_imp.4_fixed <- hot_imp.4.post[1:5] %>% posterior_summary() %>% round(3) 

#Getting the SD 
hot_imp.4_sd <- posterior_samples(hot.mod.imp.4, "sd_")
hot_imp.4_var <- hot_imp.4_sd^2 
names(hot_imp.4_var) <- str_replace(names(hot_imp.4_var), "sd", "var")
hot_imp.4_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
hot_imp.4_cov <- bind_cols(posterior_samples(hot.mod.imp.4, "cor_")[,1] * (hot_imp.4_sd[,1] * hot_imp.4_sd[,2]),
                            posterior_samples(hot.mod.imp.4, "cor_")[,2] * (hot_imp.4_sd[,3] * hot_imp.4_sd[,4]))
names(hot_imp.4_cov) <- str_replace(names(posterior_samples(hot.mod.imp.4, "cor_")), "cor", "cov")
hot_imp.4_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
hot_imp.4_residuals <- ( posterior_samples(hot.mod.imp.4, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
hot_imp.4_coeffs <- rbind(hot_imp.4_fixed,
                         hot_imp.4_var %>% posterior_summary() %>% round(3),
                         hot_imp.4_cov %>% posterior_summary() %>% signif(3),
                         hot_imp.4_residuals)

#Excluding est. error
hot_imp.4_coeffs <- hot_imp.4_coeffs[,c(1,3,4)]
#Rownames as col
hot_imp.4_coeffs <- as.data.frame(hot_imp.4_coeffs)
hot_imp.4_coeffs$Parameter <- c(rownames(hot_imp.4_coeffs))
rownames(hot_imp.4_coeffs) <- NULL 
hot_imp.4_coeffs <- hot_imp.4_coeffs[,c(4,1:3)]
```

```{r, eval = TRUE, include = TRUE}
pander(cold_imp.4_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S10 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. In this model, we fitted a 'series' as random intercept with temeperature as a random slope to estimate repeatability of the slope. See Statistical Analyses for details. This imputation model used an subset dataset of lizards in the cold developmental temperature only n = 26, n_obs = ")

pander(hot_imp.4_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S11 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. In this model, we fitted a 'series' as random intercept with temeperature as a random slope to estimate repeatability of the slope. See Statistical Analyses for details. This imputation model used an subset dataset of lizards in the hot developmental temperature only n = 25, n_obs = ")
```

```{r}
#Repeatability of the slope for each treatment
#CC
cc_cold.4.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_cold.z4.obj")
cc_hot.4.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_hot.z4.obj")

brms_rptSlope_cc(model = cc_cold.4.obj)
brms_rptSlope_cc(model = cc_hot.4.obj)
```

```{r, eval = TRUE}
#Model coefficients for hot and cold complete case that were used to estimate repeatbility of slopes
# Read in models
cc_cold.4.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_cold.z4.obj")
cc_hot.4.obj <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/cc_hot.z4.obj")

#Extract entire posterior
cc_cold.4.post <- posterior_samples(cc_cold.4.obj)
#Names of each column
colnames(cc_cold.4.post)[1:13]

#Combining the coefficients from the final model
#Getting the fixed effects
cc_cold.4_fixed <- cc_cold.4.post[1:4] %>% posterior_summary() %>% round(3) 

#Getting the SD 
cc_cold.4_sd <- posterior_samples(cc_cold.4.obj, "sd_")
cc_cold.4_var <- cc_cold.4_sd^2 
names(cc_cold.4_var) <- str_replace(names(cc_cold.4_var), "sd", "var")
cc_cold.4_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
cc_cold.4_cov <- bind_cols(posterior_samples(cc_cold.4.obj, "cor_")[,1] * (cc_cold.4_sd[,1] * cc_cold.4_sd[,2]),
                            posterior_samples(cc_cold.4.obj, "cor_")[,2] * (cc_cold.4_sd[,3] * cc_cold.4_sd[,4]))
names(cc_cold.4_cov) <- str_replace(names(posterior_samples(cc_cold.4.obj, "cor_")), "cor", "cov")
cc_cold.4_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
cc_cold.4_residuals <- ( posterior_samples(cc_cold.4.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
cc_cold.4_coeffs <- rbind(cc_cold.4_fixed,
                         cc_cold.4_var %>% posterior_summary() %>% round(3),
                         cc_cold.4_cov %>% posterior_summary() %>% signif(3),
                         cc_cold.4_residuals)
#Excluding est. error
cc_cold.4_coeffs <- cc_cold.4_coeffs[,c(1,3,4)]
#Rownames as col
cc_cold.4_coeffs <- as.data.frame(cc_cold.4_coeffs)
cc_cold.4_coeffs$Parameter <- c(rownames(cc_cold.4_coeffs))
rownames(cc_cold.4_coeffs) <- NULL 
cc_cold.4_coeffs <- cc_cold.4_coeffs[,c(4,1:3)]

#Extract entire posterior
cc_hot.4.post <- posterior_samples(cc_hot.4.obj)
#Names of each column
colnames(cc_hot.4.post)[1:13]

#Combining the coefficients from the final model
#Getting the fixed effects
cc_hot.4_fixed <- cc_hot.4.post[1:4] %>% posterior_summary() %>% round(3) 

#Getting the SD 
cc_hot.4_sd <- posterior_samples(cc_hot.4.obj, "sd_")
cc_hot.4_var <- cc_hot.4_sd^2 
names(cc_hot.4_var) <- str_replace(names(cc_hot.4_var), "sd", "var")
cc_hot.4_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
cc_hot.4_cov <- bind_cols(posterior_samples(cc_hot.4.obj, "cor_")[,1] * (cc_hot.4_sd[,1] * cc_hot.4_sd[,2]),
                            posterior_samples(cc_hot.4.obj, "cor_")[,2] * (cc_hot.4_sd[,3] * cc_hot.4_sd[,4]))
names(cc_hot.4_cov) <- str_replace(names(posterior_samples(cc_hot.4.obj, "cor_")), "cor", "cov")
cc_hot.4_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
cc_hot.4_residuals <- ( posterior_samples(cc_hot.4.obj, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
cc_hot.4_coeffs <- rbind(cc_hot.4_fixed,
                         cc_hot.4_var %>% posterior_summary() %>% round(3),
                         cc_hot.4_cov %>% posterior_summary() %>% signif(3),
                         cc_hot.4_residuals)
#Excluding est. error
cc_hot.4_coeffs <- cc_hot.4_coeffs[,c(1,3,4)]
#Rownames as col
cc_hot.4_coeffs <- as.data.frame(cc_hot.4_coeffs)
cc_hot.4_coeffs$Parameter <- c(rownames(cc_hot.4_coeffs))
rownames(cc_hot.4_coeffs) <- NULL 
cc_hot.4_coeffs <- cc_hot.4_coeffs[,c(4,1:3)]
```

```{r, eval = TRUE, include = TRUE}
pander(cc_cold.4_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S10 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. In this model, we fitted a 'series' as random intercept with temeperature as a random slope to estimate repeatability of the slope. See Statistical Analyses for details. This model used a complete case dataset of lizards in the cold developmental temperature only n = 26, n_obs = 1897")

pander(cc_hot.4_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S11 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. In this model, we fitted a 'series' as random intercept with temeperature as a random slope to estimate repeatability of the slope. See Statistical Analyses for details. This model used a complete case dataset of lizards in the cold developmental temperature only n = 26, n_obs = 1921")
```

```{r, eval = TRUE}
#Post hoc analysis to test whether treatment differences in reaction norms are found early on or later
mod.imp.3_s1 <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/mod.imp.3_s1")
mod.imp.3_s10 <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/mod.imp.3_s10")

#What is the mean age at sampling session 1 and 10
data %>% filter(samp_session == 1 | samp_session == 10) %>% 
  select(id, samp_session, treatment, age) %>% 
  distinct() %>% 
  group_by(samp_session) %>%
  summarise(mean_age = round(mean(age, na.rm = T),2),
            sd_age = round(sd(age, na.rm = T),2)) %>% 
  as.data.frame()

#Cofficients summary of sampling session 1
mod.imp.3_s1_post <- posterior_samples(mod.imp.3_s1)
names(mod.imp.3_s1_post)[1:13]

#Getting the fixed effects
mod.imp.3_s1_fixed <- mod.imp.3_s1_post[1:7] %>% posterior_summary() %>% round(3) 

#Getting the SD 
mod.imp.3_s1_sd <- posterior_samples(mod.imp.3_s1, "sd_")
mod.imp.3_s1_var <- mod.imp.3_s1_sd^2 
names(mod.imp.3_s1_var) <- str_replace(names(mod.imp.3_s1_var), "sd", "var")
mod.imp.3_s1_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
mod.imp.3_s1_cov <- bind_cols(posterior_samples(mod.imp.3_s1, "cor_") * (mod.imp.3_s1_sd[,1] * mod.imp.3_s1_sd[,2]))
names(mod.imp.3_s1_cov) <- str_replace(names(posterior_samples(mod.imp.3_s1, "cor_")), "cor", "cov")
mod.imp.3_s1_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
mod.imp.3_s1_residuals <- ( posterior_samples(mod.imp.3_s1, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
mod.imp.3_s1_coeffs <- rbind(mod.imp.3_s1_fixed,
                         mod.imp.3_s1_var %>% posterior_summary() %>% round(3),
                         mod.imp.3_s1_cov %>% posterior_summary() %>% signif(3),
                         mod.imp.3_s1_residuals)

#Excluding est. error
mod.imp.3_s1_coeffs <- mod.imp.3_s1_coeffs[,c(1,3,4)]
#Rownames as col
mod.imp.3_s1_coeffs <- as.data.frame(mod.imp.3_s1_coeffs)
mod.imp.3_s1_coeffs$Parameter <- c(rownames(mod.imp.3_s1_coeffs))
rownames(mod.imp.3_s1_coeffs) <- NULL 
mod.imp.3_s1_coeffs <- mod.imp.3_s1_coeffs[,c(4,1:3)]

#Cofficients summary of sampling session 10
mod.imp.3_s10_post <- posterior_samples(mod.imp.3_s10)
names(mod.imp.3_s10_post)[1:13]

#Getting the fixed effects
mod.imp.3_s10_fixed <- mod.imp.3_s10_post[1:7] %>% posterior_summary() %>% round(3) 

#Getting the SD 
mod.imp.3_s10_sd <- posterior_samples(mod.imp.3_s10, "sd_")
mod.imp.3_s10_var <- mod.imp.3_s10_sd^2 
names(mod.imp.3_s10_var) <- str_replace(names(mod.imp.3_s10_var), "sd", "var")
mod.imp.3_s10_var %>% posterior_summary() %>% round(3) 

#Getting the COR to cov
mod.imp.3_s10_cov <- bind_cols(posterior_samples(mod.imp.3_s10, "cor_") * (mod.imp.3_s10_sd[,1] * mod.imp.3_s10_sd[,2]))
names(mod.imp.3_s10_cov) <- str_replace(names(posterior_samples(mod.imp.3_s10, "cor_")), "cor", "cov")
mod.imp.3_s10_cov %>% posterior_summary() %>% signif(3) 

#Getting the residuals
mod.imp.3_s10_residuals <- ( posterior_samples(mod.imp.3_s10, "sigma")^2 ) %>% posterior_summary() %>% round(3) 

#Bind these together
mod.imp.3_s10_coeffs <- rbind(mod.imp.3_s10_fixed,
                         mod.imp.3_s10_var %>% posterior_summary() %>% round(3),
                         mod.imp.3_s10_cov %>% posterior_summary() %>% signif(3),
                         mod.imp.3_s10_residuals)

#Excluding est. error
mod.imp.3_s10_coeffs <- mod.imp.3_s10_coeffs[,c(1,3,4)]
#Rownames as col
mod.imp.3_s10_coeffs <- as.data.frame(mod.imp.3_s10_coeffs)
mod.imp.3_s10_coeffs$Parameter <- c(rownames(mod.imp.3_s10_coeffs))
rownames(mod.imp.3_s10_coeffs) <- NULL 
mod.imp.3_s10_coeffs <- mod.imp.3_s10_coeffs[,c(4,1:3)]
```
```{r}
#Model predictions for sampling session 1 and 10
#Setting up predictive data

s10_new_data <- mi_data %>% filter(samp_session == 10) %>% 
  mutate(series = paste0(id, "_", samp_session)) %>% 
  distinct(id, temp, treatment)

s1_new_data <- mi_data %>% filter(samp_session == 1) %>% 
  mutate(series = paste0(id, "_", samp_session)) %>% 
  distinct(id, temp, treatment)

post = mod.imp.3_s10_post

#Try pmap
s10_predictions <- bind_rows(pmap(s10_new_data, imp_ph_pred))
s10_predictions$samp_sesson <- 10

post = mod.imp.3_s1_post

s1_predictions <- bind_rows(pmap(s1_new_data, imp_ph_pred))
s1_predictions$samp_sesson <- 1

posthoc_dat <- bind_rows(s1_predictions,
          s10_predictions)

rownames(posthoc_dat) <- NULL

ggplot(data = posthoc_dat, aes(x = temp, y = mean_lnmr)) + 
  geom_line(aes(group = id, colour = factor(treatment)), stat="smooth", method = "lm", lwd = 0.5, alpha = 0.4) + 
  geom_line(aes(group = factor(treatment), colour = factor(treatment)), stat="smooth", method = "lm", lwd = 2, alpha = 1, position =position_dodge(width = 0.3)) +
  geom_point(alpha = 0.2) + 
  scale_colour_manual(values = c("#2790F3", "#F24D2A")) + 
  scale_x_continuous(breaks = c(seq(24,34, by = 2))) + 
  scale_y_continuous(lim = c(-6.6, -5.25)) + 
  facet_wrap(~samp_sesson) + 
  labs(x = "Temperature",
       y = TeX("log VCO_2 per minute"),
       #title = "Relative contribution of variance over age",
       colour =  "Treatment") + 
  theme_bw() +
  my_theme + 
  theme(legend.position = "none",
        strip.text = element_text(size = 18),
        strip.background = element_blank())

ggplot(data = s1_predictions, aes(x = temp, y = mean_lnmr)) + 
  geom_line(aes(group = id, colour = factor(treatment)), stat="smooth", method = "lm", lwd = 0.5, alpha = 0.4) + 
  geom_line(aes(group = factor(treatment), colour = factor(treatment)), stat="smooth", method = "lm", lwd = 2, alpha = 1) +
  geom_point(alpha = 0.2) + 
  scale_colour_manual(values = c("#2790F3", "#F24D2A")) + 
  scale_x_continuous(breaks = c(seq(24,34, by = 2))) + 
  scale_y_continuous(lim = c(-6.6, -5.25)) + 
  labs(x = "Temperature",
       y = TeX("log VCO_2 per minute"),
       #title = "Relative contribution of variance over age",
       colour =  "Treatment") + 
  theme_bw() +
  my_theme + 
  theme(legend.position = "none",
        strip.text = element_text(size = 18),
        strip.background = element_blank())

ggplot(data = s10_predictions, aes(x = temp, y = mean_lnmr)) + 
  geom_line(aes(group = id, colour = factor(treatment)), stat="smooth", method = "lm", lwd = 0.5, alpha = 0.4) + 
  geom_line(aes(group = factor(treatment), colour = factor(treatment)), stat="smooth", method = "lm", lwd = 2, alpha = 1) +
  geom_point(alpha = 0.2) + 
  scale_colour_manual(values = c("#2790F3", "#F24D2A")) + 
  scale_x_continuous(breaks = c(seq(24,34, by = 2))) + 
  scale_y_continuous(lim = c(-6.6, -5.25)) + 
  labs(x = "Temperature",
       y = TeX("log VCO_2 per minute"),
       #title = "Relative contribution of variance over age",
       colour =  "Treatment") + 
  theme_bw() +
  my_theme + 
  theme(legend.position = "none",
        strip.text = element_text(size = 18),
        strip.background = element_blank())
```

```{r, eval = TRUE, include = TRUE}
pander(mod.imp.3_s1_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S14 Model coefficients of model testing whether body mass, temeperature and age predicts variation in metabolic rate. This was an imputation model used a subset dataset of sampling session one only n = 25, nobs = 3000. Mass and MR was log transformed and Age was z-transformed. Bolded estimates are significantly different from zero. Values with * indicate very small values that are still greater than zero")

pander(mod.imp.3_s10_coeffs,
       justify = "lccc",
       #split.cell = 80,
       caption = "Table S15 Model coefficients of model whether body mass, temeperature and age predicts variation in metabolic rate. In this model, we fitted a 'series' as random intercept with temeperature as a random slope to estimate repeatability of the slope. See Statistical Analyses for details. This model used a complete case dataset of lizards in the cold developmental temperature only n = 26, n_obs = 1897")
```

```{r}
# Checking on White et al's meta-analysis data for ectotherms
white <- read.csv("data/white_metaanalysis.csv", stringsAsFactors = F)

ecto_white <- white %>% filter(Variable == "RMR" & Group == "Ectotherm") %>% arrange(Interval..days.)

#What is our measurement interval?
#Our interval is 5 and 12 days

ecto_white %>% filter(Interval..days. > 5) %>% 
  summarise(mean_rpt = mean(Repeatability) %>% round(2) ,
            sd_rpt = sd(Repeatability) %>% round(2))

ecto_white %>% filter(Interval..days. > 8.5) %>% 
  summarise(mean_rpt = mean(Repeatability) %>% round(2) ,
            sd_rpt = sd(Repeatability) %>% round(2), 
            n = length(Repeatability))
```

## Egg sizes and hatching success

```{r}
egg_data <- read.csv("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/data/lizard/all_eggs.csv")

#Overview
names(egg_data)
str(egg_data)

#Clean
egg_data %<>% filter(! egg_status == "AVAILABLE" &
                       ! egg_status == "CULLED" &
                       ! egg_status == "" &
                       egg_fertile_status == "fertile")

#Difference in egg sizes between treatments
egg_mass <- lm(egg_mass_orig ~ factor(egg_incub_temp), data = egg_data)
summary(egg_mass)

egg_len <- lm(egg_length_orig ~ factor(egg_incub_temp), data = egg_data)
summary(egg_len)

egg_width <- lm(egg_width_orig ~ factor(egg_incub_temp), data = egg_data)
summary(egg_width)

#Multivariate response model
egg_mass_mod <- bf(egg_mass_orig ~ factor(egg_incub_temp))
egg_len_mod <- bf(egg_length_orig ~ factor(egg_incub_temp))
egg_wid_mod <- bf(egg_width_orig ~ factor(egg_incub_temp))

#setup
# iter = 5000
# warmup = iter/2
# thin = 5
# 
# egg_dim_mvmod <- brm(formula = egg_mass_mod + egg_len_mod + egg_wid_mod,
#                      data = egg_data, family = gaussian(),
#                      cores = 3,
#                      iter = iter,
#                      warmup = warmup,
#                      thin = thin)
# 
# saveRDS(egg_dim_mvmod,

egg_dim_mvmod <- readRDS("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/output/rds/egg_dim_mvmod")

write.csv(posterior_summary(egg_dim_mvmod) %>% round(2), "output/tab/egg_brms.csv")

#Difference in hatching success
hatch_data <- egg_data %>% filter(! egg_status == "AVAILABLE" &
                                    ! egg_status == "CULLED" &
                                    ! egg_status == "" &
                                    egg_fertile_status == "fertile") #Cleaning
#Create new variable
hatch_data %<>% mutate(hatch_success = ifelse(egg_status == "DEAD", 0, 1))

hatch_suc <- glm(factor(hatch_success) ~ egg_mass_orig + egg_incub_temp, 
                 data = hatch_data,
                 family = "binomial")

summary(hatch_suc)
```

## Thermal range at a natural site - extraction of data in Cheetman et al. 2010

```{r}
metaDigitise("~/Dropbox/1 - PhD/5 - Ldeli_inc_metabTelo/data/cheetham/")
```

